USE [ITBIT]
GO

/****** Object:  Table [dbo].[sexo]    Script Date: 16/09/2021 17:47:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[sexo](
	[Sexoid] [int] NOT NULL,
	[Descricao] [varchar](15) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Sexoid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


